### //  LOGIN
POST http://localhost:3003/api/login/
Content-Type: application/json

{
    "email": "testi@testi.com",
    "password": "asdasdasd"
} 

### //  CREATE A NEW USER
POST http://localhost:3003/api/users/
Content-Type: application/json

{
    "email": "testi@testi.com",
    "name": "Testeri Testimies",
    "password": "eees",
    "type_id": 1
} 
### //  GET ALL USERS
GET http://localhost:3003/api/users/

### //  UPDATE AN EXISTING NOTE
POST http://localhost:3003/api/notes/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RpQHRlc3RpLmNvbSIsImlkIjoxLCJpYXQiOjE2NDU1NjMxOTd9.iNCDbIczJtIhAAvvvqR8Y1HSUVCb-mv3lJxRIkN1P0E

{

    "title": "aaaaaaaaaaaaaaaaaaaaaaa",
    "content": "blaal lbasld asidj alsidsaskdjalskd asld jals kjas asdl iajs",
    "id": 
} 

### //  CREATE A NEW NOTE
POST http://localhost:3003/api/notes/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RpQHRlc3RpLmNvbSIsImlkIjoxLCJpYXQiOjE2NDU1NjMxOTd9.iNCDbIczJtIhAAvvvqR8Y1HSUVCb-mv3lJxRIkN1P0E

{
    "title": "aaaaaaaaaaaaaaaaaaaaaaa",
    "content": "blaal lbasld asidj alsidsaskdjalskd asld jals kjas asdl iajs"
} 

### //  GET ALL NOTES OF USER WHO IS LOGGED IN
GET http://localhost:3003/api/notes/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RpQHRlc3RpLmNvbSIsImlkIjoxLCJpYXQiOjE2NDU1NjM3NjJ9.-Y1D2Lm5yfTkpVa0fzHZFwC0CgjsYW3XNtmYJwv61nQ

